FROM python:3.12-slim

WORKDIR /app

COPY ./consumer/requirements.txt .
COPY ./consumer/ingest_consultations.py .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "ingest_consultations.py"]
