FROM apache/airflow:3.1.5

USER root

USER airflow

# Install dbt and other dependencies
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r ./requirements.txt

RUN pip install --no-cache-dir xgboost==3.1.2
RUN pip install --no-cache-dir scikit-learn==1.6.1
RUN pip install --no-cache-dir mlflow-skinny==3.8.0

USER airflow

