FROM python:3.12-slim

WORKDIR /app

COPY ./webapp .
COPY ./webapp/requirements.txt ./webapp/requirements.txt
COPY ./webapp/utils ./webapp/utils
COPY ./webapp/consultation_cursor.txt ./webapp/consultation_cursor.txt

COPY ./data/consultations.json ./data/consultations.json

RUN pip install --no-cache-dir -r ./webapp/requirements.txt

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8000"]